{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 243947,
          "sha512": "d2a9d346961191aeaca71cc4787a3cfa840b45cf80a4e6d60af81d3e7a33037c6f76c518c784f9beb99d9d457ce8f465c9fca7a487e54b0eded808ebb9fe0419",
          "sha256": "d1cc9e809fc1148903a86c0ac37a9b356d179952d502ad895ced8fbd8b6ea635",
          "sha1": "ca753236cbeac9e5ffef77d378a76b1f595677c3",
          "md5": "8cd428f7261b938b8139f4eedbf311e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 243947,
          "sha512": "d2a9d346961191aeaca71cc4787a3cfa840b45cf80a4e6d60af81d3e7a33037c6f76c518c784f9beb99d9d457ce8f465c9fca7a487e54b0eded808ebb9fe0419",
          "sha256": "d1cc9e809fc1148903a86c0ac37a9b356d179952d502ad895ced8fbd8b6ea635",
          "sha1": "ca753236cbeac9e5ffef77d378a76b1f595677c3",
          "md5": "8cd428f7261b938b8139f4eedbf311e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 73759,
          "sha512": "65394d85f12eb52c26304f19787f3c9bd2b46ecbd34e400668c417019c73f388a9e14e68117ebb0e2fae245c9c72092c3200147bbf6af80d2f1adc7d46a67a51",
          "sha256": "f4025874a6f89bf4674438965408ea270a784712e9fbc0927ed7c8803f0f0441",
          "sha1": "45e6c592c2ce1fe53af11d48188a74de8b76c691",
          "md5": "c14d1fb55ee9056e7da589c3cb8bbd01"
        }
      ]
    }
  ]
}
