{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246327,
          "sha512": "491bdc7f55156fcaf08f51d77814bf34274fc75b82f7a72d5a93f674806fd29d31b38a969fd17b670d898924b868d81c636ba3bf0a1b168a869fac8ccb51d459",
          "sha256": "e6fa0fc76b3211dd18c0a3cfb27b9153ebe29c7ce951cc5cb5a17e5fb9576c73",
          "sha1": "b005d9e2cdcd774b7c2a7df927b18ef725e5be92",
          "md5": "d1c312a494113ae4841b7336a802f811"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 246327,
          "sha512": "491bdc7f55156fcaf08f51d77814bf34274fc75b82f7a72d5a93f674806fd29d31b38a969fd17b670d898924b868d81c636ba3bf0a1b168a869fac8ccb51d459",
          "sha256": "e6fa0fc76b3211dd18c0a3cfb27b9153ebe29c7ce951cc5cb5a17e5fb9576c73",
          "sha1": "b005d9e2cdcd774b7c2a7df927b18ef725e5be92",
          "md5": "d1c312a494113ae4841b7336a802f811"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 70395,
          "sha512": "a3ef9d76645291753dc6352c9404de3d19f4c5c5183f380d02fda584e5131eb33ae9e97bd8531fc0b59145c950c009c0a3cfb26fb503be65fe2753b4766a2edd",
          "sha256": "7340fcd3d18cd161bb031de5c077027c038e069d0afb4b4c47eb7d1709f27bce",
          "sha1": "648988c5c65661e3fe6acc1fe019f7e8cfbd854c",
          "md5": "c8f71764eb10b9144d9f2226e45ac385"
        }
      ]
    }
  ]
}
