{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 247647,
          "sha512": "5835d00c5bf76a5bc20dcae5be2fe936aeaeeaeb69e0d906313ace79388940d2842b766d7a9bb788e8efb213fcb7652e13a4fafbf46bbfc74f6422dd21bf2a8e",
          "sha256": "a3f8b9ab93fe9abb73744aa89a082a56cca5cf567afeeee20aa3ff6bc37c7181",
          "sha1": "13a077c27cd4ba5f5da3c228814481f8bcf37b5c",
          "md5": "c618ee702771e6a246e1575d25a9fa57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 247647,
          "sha512": "5835d00c5bf76a5bc20dcae5be2fe936aeaeeaeb69e0d906313ace79388940d2842b766d7a9bb788e8efb213fcb7652e13a4fafbf46bbfc74f6422dd21bf2a8e",
          "sha256": "a3f8b9ab93fe9abb73744aa89a082a56cca5cf567afeeee20aa3ff6bc37c7181",
          "sha1": "13a077c27cd4ba5f5da3c228814481f8bcf37b5c",
          "md5": "c618ee702771e6a246e1575d25a9fa57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 70696,
          "sha512": "8b04415be79821047e39ceab0c94e5db84e9826c53b23d97500a5f7baa6b6f1e46a6b858f5de20e0456cd21294440ff7cd3df124157e9d29582b7203cd251141",
          "sha256": "8ad866d90f42e707a10b646a60b405880d89c297cce61417714f05ec174b9d2c",
          "sha1": "0366417c9aeb60a4d17150c587125b36a3304cd4",
          "md5": "a56b667fb2fae0a6beaa9c62a64a379f"
        }
      ]
    }
  ]
}
