{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 244072,
          "sha512": "d1c3c506be4ce3998b9b03bf47b6c65a544eb368a462f3933354c3d623efa42b8336738ab1d21bfef96757b10ed1f3967e862b423705a0ab11f63dbb861f25f1",
          "sha256": "c63b3e18de732fe362e43190a610fa437bc65607d2406c1e378223fd867f1541",
          "sha1": "39dc3d47cc5235c33df12affe0145e6c92a24ba6",
          "md5": "d99a93d4f20063cde34c46b7761b5e99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 244072,
          "sha512": "d1c3c506be4ce3998b9b03bf47b6c65a544eb368a462f3933354c3d623efa42b8336738ab1d21bfef96757b10ed1f3967e862b423705a0ab11f63dbb861f25f1",
          "sha256": "c63b3e18de732fe362e43190a610fa437bc65607d2406c1e378223fd867f1541",
          "sha1": "39dc3d47cc5235c33df12affe0145e6c92a24ba6",
          "md5": "d99a93d4f20063cde34c46b7761b5e99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 73742,
          "sha512": "2bd68f87cd620a7213dc9bdc5ff32392531d1b8073417f1ff6d2c4f576a3196f978af3123c56af650b8290b92e86f975f10ddc29b67eacf9759e2dbe9d22cbb3",
          "sha256": "9b1537d70f028df94fac6095620e299a4cb38ed32b023cbcb73653153b575d26",
          "sha1": "88daf5232157af59cf972599f7c00f6d3c2719aa",
          "md5": "7e745070f241b32ed6ae237112c51d91"
        }
      ]
    }
  ]
}
