{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 245971,
          "sha512": "1fd5f43de612b022a2d24985333c2f6e5255825c60aefb04514e3ff399652c9bd246a366fbf02f6bb086160440e3f9e787eafa68d249f99ef9945b56ea653a52",
          "sha256": "8b88b8eed0a202b3661acd4585c5397173320def98e21f6aa4e2e7a63b35eef1",
          "sha1": "a6a664ec4969151cad10e96029de662b360b3a81",
          "md5": "337d2beb2c5189066075a9d1c0735a34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 245971,
          "sha512": "1fd5f43de612b022a2d24985333c2f6e5255825c60aefb04514e3ff399652c9bd246a366fbf02f6bb086160440e3f9e787eafa68d249f99ef9945b56ea653a52",
          "sha256": "8b88b8eed0a202b3661acd4585c5397173320def98e21f6aa4e2e7a63b35eef1",
          "sha1": "a6a664ec4969151cad10e96029de662b360b3a81",
          "md5": "337d2beb2c5189066075a9d1c0735a34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 74266,
          "sha512": "59590cf1d940d2e0321a3ff6b5efee43e412f8ca5908cdfd27f52ecb758bffa8d2b161fcac6570eb456a6117ef29b3ea7bd7614f92ff29e8a589bf14ea66a3d4",
          "sha256": "cafdc045155dbbace92d36b4a3ab5e3f768fdc956826d3c0c79256ec64133691",
          "sha1": "8a2336a83b16e1c7d2e8db324a2ed7cc7906b993",
          "md5": "64dace270b5aa98a4f24b3038bfabc51"
        }
      ]
    }
  ]
}
