{
  "formatVersion": "1.1",
  "component": {
    "group": "io.liveness.flash",
    "module": "sdk-android",
    "version": "v1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 244123,
          "sha512": "9280c5438997c5b0af1300e158f95a1e05e612ca7e2fb968a68f0dba62116e0c8cf6cce66965f31f7a822429240320ab86d88a755621fb5646c1b265d3186e08",
          "sha256": "967abfb8f23e2ea8cd955065c6cce4f592a3b6574548ad3b7def295a619db1b2",
          "sha1": "3e567f85ba6bdf5d4f8c3ee251dcb09a3f2278ce",
          "md5": "ca0450500bcbfd2f9a9af99e2215f87b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.5"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.31"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-v1.1.9.aar",
          "url": "sdk-android-v1.1.9.aar",
          "size": 244123,
          "sha512": "9280c5438997c5b0af1300e158f95a1e05e612ca7e2fb968a68f0dba62116e0c8cf6cce66965f31f7a822429240320ab86d88a755621fb5646c1b265d3186e08",
          "sha256": "967abfb8f23e2ea8cd955065c6cce4f592a3b6574548ad3b7def295a619db1b2",
          "sha1": "3e567f85ba6bdf5d4f8c3ee251dcb09a3f2278ce",
          "md5": "ca0450500bcbfd2f9a9af99e2215f87b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-android-v1.1.9-sources.jar",
          "url": "sdk-android-v1.1.9-sources.jar",
          "size": 73773,
          "sha512": "e2e0d28371c15dadf2c6e0075dd078bda774d8f5294b112f57161afc3f5b199abf134179fd9fa8accba97719141e03377fb9c96029a6bcef5e07b1c6e0f19349",
          "sha256": "98512d4ab3e9aefbd6d8a836dfbe581e5cd3039a5bbf91e6177b1871d665d7ca",
          "sha1": "5856e7d6aa8c43cc9d59c7386d66958fe172bef0",
          "md5": "1cd6bd1f765ae79b143871d263d3a5b4"
        }
      ]
    }
  ]
}
